# Generated by Django 5.1.7 on 2025-03-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    # dependencies = [
    #     ('myhello', '0001_initial'),
    # ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='content',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='location',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='photo',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='title',
        # ),
        migrations.AddField(
            model_name='post',
            name='coursetitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
